#pragma once
UNICODE_STRING devname = RTL_CONSTANT_STRING(L"\\Device\\d_CIA");
UNICODE_STRING symlink = RTL_CONSTANT_STRING(L"\\??\\d_CIA");
PDEVICE_OBJECT deviceobj = NULL;
#define IOCTL_CIA_CONTROL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)